# version: "3"
#services:
  app:
    container_name: app_node
    restart: always
    build: ./api
    ports:
      - "4000:4000"
    #depends_on:
    links:
      - mongo_node
  client:
    container_name: client_node
    restart: always
    build: ./client
    ports:
      - "3000:3000"
    links:
      - app_node
  mongo:
    container_name: mongo_node
    image: mongo
    restart: always
    expose:
      - "27017"
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
